name: Header
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone repository
        run: |
            git clone https://github.com/abagreenambassadors/abagreenambassadors.github.io
            cd abagreenambassadors.github.io
      - name: Replace text
      - if: always()
        run: |
            for i in $(find . -not -path '*/\.*'); do
              if [[ $i == *"html" ]]; then
                grep '.*<head>.*' $i --quiet
                if [ $? = 1 ]; then
                    cp .github/workflows/header.txt $i-header.html
                    cat $i >> $i-header.html
                    #mv $i-header.html $i
                fi
              fi
            done
      - name: Push changes
        run: |
            git add .
            git commit -m "Github CI: Add header to files"
            git push
