name: Header
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          for i in $(find . -not -path '*/\.*'); do
            pwd
            ls
            if [[ $i == *"html" ]]; then
              grep '<head>' $i
              if [ $? = 1 ]; then
                pwd
                ls
                sed -i -e "1i `cat .github/workflows/header.txt`" $i
              fi
            fi
          done
