name: Header
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Make changes and push
        run: |
            git clone https://github.com/abagreenambassadors/abagreenambassadors.github.io
            cd abagreenambassadors.github.io
            for i in $(find . -not -path '*/\.*' -iname '*.html'); do
              echo $i
              grep '.*<head>.*' $i --quiet
              if [[ $? == 1 ]]; then
                  cp .github/workflows/header.txt $i-header.html
                  cat $i >> $i-header.html
                  #mv $i-header.html $i
              fi
            done
            git add .
            git commit -m "Github CI: Add header to files"
            git push
