name: Header
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
            for i in $(find . -not -path '*/\.*'); do
              if [[ $i == *"html" ]]; then
                grep '.*<head>.*' $i --quiet
                if [ $? = 1 ]; then
                    cp .github/workflows/header.txt $i-header.html
                    cat $i >> $i-header.html
                    #mv $i-header.html $i
                fi
              fi
            done
