name: Header
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make changes and push
        run: |
         for i in $(find . -not -path '*/\.*' -iname '*.html'); do
             if ! grep -q '<title>Al Bateen Green Ambassadors site</title>' $i; then
                 cp .github/workflows/header.txt $i-header.html
                 cat $i >> $i-header.html
                 mv $i-header.html $i
             fi
         done
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         git commit -m "Github CI: Add header to files"
         git push
