name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pandoc
        run: |
         sudo apt install pandoc
         for i in $(ls blog/*.md); do
             pandoc $i -o $i.html
         done
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         git commit -m "Github CI: Convert files"
         git push
      - name: Append header
        run: |
         for i in $(find . -not -path '*/\.*' -iname '*.html'); do
             if ! grep -q '<title>Al Bateen Green Ambassadors site</title>' $i; then
                 cp .github/workflows/header.txt $i-header.html
                 cat $i >> $i-header.html
                 mv $i-header.html $i
             fi
         done
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         git commit -m "Github CI: Add header to files"
         git push
      - name: Index posts
        run: |
         pwd
         for i in $(ls -1 ./blog/*.html); do
           if ! grep -q "$i" ./blog.html; then
            sed -i "/<h1>/a \<a href=$i\>$i\<\/a\>" ./blog.html
           fi
         done
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         git commit -m "Github CI: Add blog entries"
         git push
