name: Pandoc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pandoc
        run: |
          sudo apt install pandoc
          for i in $(ls blog/*.md); do
              pandoc $i -o $i.html
          done
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Github CI: Convert files"
          git push
