name: Posts
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make changes and push
        run: |
         pwd
         for i in $(ls -1 ./blog/*.html); do
             sed -i "/<h1>/a \<a href=$i\>$i\<\/a\>" ./blog.html
         done
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         git commit -m "Github CI: Add blog entries"
         git push
