name: Posts
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make changes and push
        run: |
         for i in $(ls blog/*.html); do
             sed "/\<a href=$i\>$i\<\/a\>/a \<h1\>" blog.html
         done
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add .
         git commit -m "Github CI: Add blog entries"
         git push
